server:
  port: 8081

spring:
  application.name: wallet-service
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/test
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9093
          autoCreateTopics: false
          transaction:
            transaction-id-prefix: wallet-
            producer:
              configuration:
                transaction:
                  timeout:
                    ms: 30000

        bindings:
          consume-in-0:
            consumer:
              enable-dlq: true
              dlq-name: payment_wallet_dlq

      bindings:
        consume-in-0:
          destination: payment
          group: wallet-service
          consumer:
            max-attempts: 3

logging:
  level:
    org.springframework:
      transaction: TRACE
      orm.jpa: DEBUG
      kafka: TRACE

