server:
  port: 8080

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/test
    username: root
    password: 1234

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9093
          autoCreateTopics: false
        bindings:
          send-out-0:
            producer:
              record-metadata-channel: payment-result

      bindings:
        send-out-0:
          destination: payment
          group: payment-service

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.r2dbc: DEBUG
    org.springframework.transaction: DEBUG

PSP:
  toss:
    url: https://api.tosspayments.com
    secretKey: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6

management:
  endpoint:
    web:
      exposure:
        include: bindings